mutation removePerson($id: ID!, $pageNumber: Int!) {
  removePerson(id: $id, pageNumber: $pageNumber) {
    id
    birthYear
    eyeColor
    gender
    hairColor
    height
    name
    skinColor
  }
}
