#import "../domains/people/types.gql"

type Query {
  people(pageNumber: Int): [Person!]!
}

type Mutation {
  addPerson(person: PersonInput!, pageNumber: Int!): [Person!]!
  removePerson(id: ID!, pageNumber: Int!): [Person!]!
  updatePerson(id: ID!, person: PersonInput!, pageNumber: Int!): [Person!]!
}

type Subscription {
  peopleUpdated: [Person!]!
}
